### PR TITLE
Test ci

### PR DESCRIPTION
**Pull request by maxired**
Hey,

this is my understanding of what whould be done to fix https://github.com/mcollina/levelgraph/issues/149.
This is following discussion on  #150

### CODE REVIEW

**Comment by mcollina** [comment]
The tests are not running on saucelabs: https://travis-ci.org/mcollina/levelgraph/jobs/171782745#L391-L397

**Comment by maxired** [comment]
Is the ` SAUCE_USERNAME` env defined in Circle CI ?
When I tried to set it locally, the test web test are executed.

**Comment by mcollina** [comment]
Let's try merging.

**Comment by maxired** [comment]
Looks like this works

**Comment by mcollina** [comment]
Indeed! Thanks!!!

**Pull request merged**
