### PR TITLE
Allow non-array search parameter.

### PR DESCRIPTION
**Pull request by jmatsushita**
This fails levelgraph-jsonld tests when updating dependencies. Just added a test and will submit a fix.

### CODE REVIEW

**Comment by mcollina** [comment]
Can you remove node v0.10 and v0.12 from `.travis.yml`? We will bump the major here as well.

**Comment by jmatsushita** [comment]
I'll bump the major and start a CHANGELOG

**Comment by mcollina** [comment]
@jmatsushita there is no need for a changelog, we have https://github.com/mcollina/levelgraph/releases.

**Comment by jmatsushita** [comment]
Ok sounds good. Hmm... Could [this error](https://travis-ci.org/mcollina/levelgraph/jobs/190568738#L1042) be `level-test` again?

**Comment by mcollina** [comment]
yes, probably.

**Comment by jmatsushita** [comment]
Seems to have done the trick.

**Pull request merged**
